version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS=redis
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: chanping.${DOMAIN_NAME:-localhost}, www.chanping.${DOMAIN_NAME:-localhost}"

networks:
  web:
    external: true
