version: '3'

services:
  redis:
    image: redis
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS=redis
    networks:
      - proxytanet
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: chanping.${DOMAIN_NAME:-localhost}, www.chanping.${DOMAIN_NAME:-localhost}"
      - "traefik.docker.network=proxytanet"

networks:
  proxytanet:
    external: true
